departamentos = [
    {value:"01", text:"Guatemala"},
    {value:"02", text:"El Progreso"},
    {value:"03", text:"Sacatepequez"},
    {value:"04", text:"Chimaltenango"},
    {value:"05", text:"Escuintla"},
    {value:"06", text:"Santa Rosa"},
    {value:"07", text:"Solola"},
    {value:"08", text:"Totonicapan"},
    {value:"09", text:"Quetzaltenango"},
    {value:"10", text:"Suchitepequez"},
    {value:"11", text:"Retalhuleu"},
    {value:"12", text:"San Marcos"},
    {value:"13", text:"Huehuetenango"},
    {value:"14", text:"El Quiche"},
    {value:"15", text:"Baja Verapaz"},
    {value:"16", text:"Alta Verapaz"},
    {value:"17", text:"El Peten"},
    {value:"18", text:"Izabal"},
    {value:"19", text:"Zacapa"},
    {value:"20", text:"Chiquimula"},
    {value:"21", text:"Jalapa"},
    {value:"22", text:"Jutiapa"}
]